services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"

  app:
    build: .
    container_name: "app"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: "db"
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:
