"""Added user reference to Assistant

Revision ID: 349cf093c91b
Revises: 6b15ec8231f9
Create Date: 2025-03-07 10:21:22.610254

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "349cf093c91b"
down_revision: Union[str, None] = "6b15ec8231f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_username_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_username_key", "user", ["username"])
    # ### end Alembic commands ###
