"""remove collection name field

Revision ID: b0c03843ebd8
Revises: c8be03925d14
Create Date: 2025-03-11 06:43:45.156712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0c03843ebd8"
down_revision: Union[str, None] = "c8be03925d14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistant", "vector_store_collection_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistant",
        sa.Column(
            "vector_store_collection_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
