"""Added voice in assistant

Revision ID: c8be03925d14
Revises: da31716dca85
Create Date: 2025-03-10 08:31:53.550640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8be03925d14"
down_revision: Union[str, None] = "da31716dca85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistant", sa.Column("voice", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistant", "voice")
    # ### end Alembic commands ###
